name: 'my_dbt_project'
version: '1.0'
profile: 'default'

# Configuring the directories for your models, snapshots, tests, and more
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Configuring the target and clean
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  my_dbt_project:
    example:
      materialized: view
